### PR TITLE
Verify Seed Is Working And Merge Please!

### PR DESCRIPTION
**Pull request by ravishrawal**

### CODE REVIEW

**Review by lc9900 — APPROVED** [review]
This looks good to me. 
One tiny thing, maybe we want to include seeding as well for production, and not just start:dev. But that's minor detail. I am ok to merge.

**Comment by TechieQian** [comment]
Also we now have both npm start:dev and npm test. Lets collapse it into one command before we commit.

**Review by TechieQian — CHANGES_REQUESTED** [review]
make npm test and start:dev into a single command.

**Comment by lc9900** [comment]
good point. Use start:dev, since we are more used to it. Test can be reserved for automated tests.

**Pull request closed without merging**
